###
@host = https://localhost:7086

## GET request for events
GET {{host}}/event/
Accept: application/json
###

## POST for adding new event
POST {{host}}/event/create/
Content-Type: application/json

{
  "name": "My second event",
  "dateStart": "2025-08-08T19:00:21.880305",
  "dateEnd": "2025-08-15T19:00:21.888724",
  "hourMask": 85
}
